# Generated by Django 4.0.4 on 2022-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220429_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('colour', 'colour'), ('Samyak', 'Samyak'), ('yash', 'yash'), ('yash2', 'yash2'), ('yash3', 'yash3'), ('yash4', 'yash4')], max_length=20),
        ),
    ]
