# Generated by Django 4.0.4 on 2022-04-30 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_category'),
        ('blog', '0011_post_likes'),
    ]

    operations = [
    ]
