# Generated by Django 3.2.13 on 2022-04-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_category'),
        ('blog', '0011_post_likes'),
    ]

    operations = [
    ]
